root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
cmd = "go build -o ./cmd/api/main ."
bin = "tmp/main"
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
include_ext = ["go", "tpl", "tmpl", "html"]
delay = 1000
kill_delay = "500ms"

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"